version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    networks:
      - microservice-network

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./bff:/app
      - bff_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - microservice-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - bff
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  frontend_node_modules:
  bff_node_modules: