[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.13.0"
prost = "0.13.5"
tokio = { version = "1.44.1", features = ["full"] }

[build-dependencies]
tonic-build = "0.13.0"

[[bin]]
name = "grpc-server"
path = "src/server.rs"

